name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Check Code Formatting
        run: ./mvnw -B spotless:check
      - name: Build
        run: ./mvnw -B -DskipTests package
      - name: Test
        run: ./mvnw -B test
